In [28]:
import numpy as np
import csv

In [29]:
a1 = np.ones((2,3))
a1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
a2 = np.ones((4,3))*5
a2

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [31]:
a2 + a2

array([[10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.],
       [10., 10., 10.]])

In [35]:
a3 = np.random.random((3,4,2))
a3

a4 = np.random.random((4,2))
a4

a3 

array([[[0.92520429, 0.88264625],
        [0.83795348, 0.83938864],
        [0.14337386, 0.54520536],
        [0.69339564, 0.19474668]],

       [[0.20631575, 0.69156987],
        [0.21489841, 0.92689537],
        [0.85058844, 0.25271983],
        [0.0533845 , 0.08503177]],

       [[0.3396209 , 0.54873376],
        [0.16244615, 0.77938629],
        [0.61739624, 0.6458166 ],
        [0.2020517 , 0.73240437]]])

In [33]:
a4

array([[0.77828417, 0.01978605],
       [0.46335938, 0.27692509],
       [0.94675479, 0.12946113],
       [0.02446998, 0.17067652]])

In [38]:
a4.T + a3.T

ValueError: operands could not be broadcast together with shapes (2,4) (2,4,3) 